server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Esta es la magia para que funcionen las rutas de Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}