version: '3.8'

services:
  # --- 1. FRONTEND (Angular) ---
  # Añadido para que la web funcione en Docker
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tfm_frontend
    ports:
      - "4200:80" # Mapeamos puerto 80 del contenedor al 4200 de tu Mac
    depends_on:
      - api

  # --- 2. API  ---
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: tfm_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models 
      - ./logs:/app/logs
    environment:
      # RUTA DEL MODELO
      - MODEL_PATH=/app/models/lstm_rul.keras
     

  # --- 3. PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  # --- 4. GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # EXTRA: El trainer se queda aquí por si se quiere ejecutar manualmente, 
  # pero no bloquea el inicio automático.
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: tfm_trainer
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./models:/app/models
    profiles: ["training"] # Esto hace que solo arranque si lo pides explícitamente

volumes:
  grafana_data: