FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dependencias mínimas
RUN apt-get update && apt-get install -y \
    build-essential \
    make \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/app/src"

# AHORA SÍ: Ejecución directa sin trucos raros
CMD ["python", "src/modelo_ia/modelo_2.py"]