FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/app/src"

EXPOSE 8000

# Fíjate: Solo hay UN "CMD" al principio de la línea
CMD ["uvicorn", "src.api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]