FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# --- CAMBIO IMPORTANTE ---
# Antes: COPY requirements.txt .
# Ahora: Apuntamos a la carpeta environment donde estás guardando las cosas
COPY environment/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/app/src"

EXPOSE 8000

CMD ["uvicorn", "src.api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]