version: '3.8'

services:
  # 1. ENTRENADOR (Genera el modelo)
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: tfm_trainer
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./models:/app/models
    

  # 2. API (Consume el modelo)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: tfm_api
    ports:
      - "8000:8000"
    volumes:
      # 1. Para leer los datos de test si los necesita
      - ./output:/app/output
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - trainer
    environment:
      # CORREGIDO: Ahora el modelo está en /app/models, no en output
      - MODEL_PATH=/app/models/lstm_rul.keras