{
 "title": "TFM-Motores",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tráfico RPM (Request Per Minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{handler=\"/predict\"}[30s])) * 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia \"media\"",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_sum[1m]) / rate(http_request_duration_highr_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estado del servicio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"fastapi_metricas\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}